### ISSUE TITLE
GameAI Jam Presentation

### ISSUE THREAD

**Issue by LJArendse** [gameaischool2021members/change#15]
Overview:
- [x] Update main README.md  project overview
- [x] Update main README.md with domain description overviews
- [x] Add team member section
- [x] Add motivation why companion agents
- [x] Add motivation for why collaborative companion domains

**Comment by LJArendse** [comment]
@ChristianCecconi thanks for the help, I've assigned you to the Issue.

**Comment by ChristianCecconi** [comment]
A proposal for "Add motivation why companion agents":

**Why companion agents?**

Cooperation between human agents and artificial intelligence is a topic of great scientific interest, especially due to its complexity, in particular for the need to advance the AI natural-language understanding (Dafoe et al., 2021).

It has been pointed out that a team composed of an AI and a human agent is more efficient than a team composed of only humans, even if humans seem to have better opinions on human partners, considering them more pleasant and creative compared to AI (Ashktorab et al., 2020; McNeese et al., 2021).

Based on what has emerged, we believe that cooperation between humans and AI is the future, to be able to establish cooperation that allows us to achieve otherwise impossible goals, combining the qualities of the human being and the growing power of artificial intelligence.

**Comment by ChristianCecconi** [comment]
I rewrote the section "Inspirational Research on Human-AI Communication / Collaboration" Using the classic APA scientific citation format, in case we want to use this instead of links:

**Inspirational Research on Human-AI Communication/Collaboration**

Ashktorab, Z., Liao, Q. V., Dugan, C., Johnson, J., Pan, Q., Zhang, W., Kumaravel, S., Campbell, M. (2020) Human-AI Collaboration in a Cooperative Game Setting: Measuring Social Perception and Outcomes. In Proceedings of the ACM on Human-Computer Interaction, 4(CSCW2), pp. 1-20. https://doi.org/10.1145/3415167
Bansal, G., Nushi, B., Kamar, E., Horvitz, E., Weld, D. S. (2021) Is the Most Accurate AI the Best Teammate? Optimizing AI for Teamwork. In ArXiv, abs/2004.13102v3.
Dafoe, A., Bachrach, Y., Hadfield, G., Horvitz, E., Larson, L.,  Graepel, T. (2021) Cooperative AI: machines must learn to find common ground. In Nature, 593(7857), pp. 33-36. doi: 10.1038/d41586-021-01170-0.
McNeese, N. J., Schelble, B. G., Canonico, L. B., Demir, M. (2021) Who/What is My Teammate? Team Composition Considerations in Human-AI Teaming. In ArXiv, abs/2105.11000v1.
Schelble, B. G., Flathmann, C., McNeese, N., Canonico, L. B. (2021). Understanding Human-AI Cooperation Through Game-Theory and Reinforcement Learning Models. In  Proceedings of the 54th Hawaii International Conference on System Sciences | 2021. DOI:10.24251/HICSS.2021.041
